# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82cdf1cede629cdb1c33bf3fbc2858377c2a07187ede3a388d550039139bbc22b5602d872c0746c77a12fd77a4f5a76719701ab67a9dc4de419098c5c3de4368

test:
  secret_key_base: 85051f2ee314adc110f9e0bca6cc2ee43ab03301d0d0772a3db1fe4a79fadcfeae16b6a6cdc517cb21b281991b48df2071327a8c45fd36b450ce516f2adcae38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
